go-goldmerchant-upscale:
  AdjustmentType: PercentChangeInCapacity
  AdjustmentValue: 65
  Cooldown: 60
  MetricItem: CpuUtilization
  Condition: Average
  ComparisonOperator: ">="
  Threshold: 60.0
  TriggerAfter: 3
  RefreshCycleSeconds: 60
  
go-goldmerchant-downscale:
  AdjustmentType: PercentChangeInCapacity
  AdjustmentValue: -20
  Cooldown: 60
  MetricItem: CpuUtilization
  Condition: Average
  ComparisonOperator: "<="
  Threshold: 20.0
  TriggerAfter: 3
  RefreshCycleSeconds: 60