go-test-unadded-upscale:                      # Will try to find go-test-unadded scaling group and ask user if they want to add
  AdjustmentType: PercentChangeInCapacity     # this upscale rule into that scaling group (only if that scaling group exists)
  AdjustmentValue: 50
  Cooldown: 60
  MetricItem: CpuUtilization
  Condition: Average
  ComparisonOperator: ">="
  Threshold: 60.0
  TriggerAfter: 3
  RefreshCycleSeconds: 60