go-testapp-downsdfadkf:                       # Examples of bad name, won't work
  AdjustmentType: PercentChangeInCapacity
  AdjustmentValue: -20
  Cooldown: 60
  MetricItem: CpuUtilization
  Condition: Average
  ComparisonOperator: "<="
  Threshold: 20.0
  TriggerAfter: 3
  RefreshCycleSeconds: 60
  
go-testapp-upscale:                           # Good, go-testapp follows the convention, be like go-testapp
  AdjustmentType: PercentChangeInCapacity
  AdjustmentValue: 45
  Cooldown: 60
  MetricItem: CpuUtilization
  Condition: Average
  ComparisonOperator: ">="
  Threshold: 61.0
  TriggerAfter: 3
  RefreshCycleSeconds: 60