wp-promo-as-new-upscale:
  AdjustmentType: PercentChangeInCapacity
  AdjustmentValue: 50
  Cooldown: 60
  MetricItem: CpuUtilization
  Condition: Average
  ComparisonOperator: ">="
  Threshold: 80.0
  TriggerAfter: 3
  RefreshCycleSeconds: 60